### PR TITLE
Bootstrap style

### PR DESCRIPTION
**Pull request by Tehiro**

### CODE REVIEW

**Comment by Tehiro** [comment]
In dev - not now

**Comment by brunnopleffken** [comment]
Nice, I'll wait for it!

**Comment by Tehiro** [comment]
I think that you manage to make support for custom styles. :)
Can give the ability to use your own div for "content"?

**Comment by brunnopleffken** [comment]
Yes, all CSS classes are customizable to make support for templates/skins, like light and dark skins, etc.
By div for content, do you mean, a custom CSS class for "content" or something?

**Comment by Tehiro** [comment]
My mistake. I looked bad. Now I think about the look :)

**Pull request closed without merging**
