### PR TITLE
Update Usercp.php

### PR DESCRIPTION
**Pull request by halojoy**
When updating members profile, to avoid database error,
I used this fix.
It is like those several issues I have had before.
When an integer field does not get NULL or Integer.

I don't know if it is only for me, but Think like this:
Can it happen for him, then it can happen for others.
These database errors.

### CODE REVIEW

**Comment by brunnopleffken** [comment]
Sounds nice! Although I still don't understand why this happens just with birthdate (member profile has many integer NULL fields)... By the way, an empty `Http::Request()` automatically returns false, so you can just do:

```php
Http::Request("field_name") ? Http::Request("field_name") : NULL;
```

Just put it inside the `array()` construct to make it ready to merge!
And thanks man, you're contributing A LOT to this project! ;)

**Comment by halojoy** [comment]
I will do  that.
Unfortunately my code did not work well.
I will try your code.

**Comment by brunnopleffken** [comment]
I think you need to add this fix inside `array()`, otherwise you fix will be overwritten.
And there's no need to close this PR, just perform another commit and this one will be updated...

**Comment by halojoy** [comment]
I think I will delete my fork.
If I have any suggestions I can always open a new fork.

**Comment by halojoy** [comment]
It did not work. Seems not even NULL is accepted.
But this worked:
"b_day"        => Http::Request("b_day")  ? Http::Request("b_day")   : 0,

**Comment by brunnopleffken** [comment]
With this fix I think the date will be shown as January 1st because it will run `mktime(0, 0, 0)` on User CP (ref. this commit 9eabcac5582594aeaae0f65a5b067f605dae249b)... But I can workaround on it (on Html.php), to show blank if value is zero!

Can you send this commit?

**Pull request merged**
