### PR TITLE
Articles | Update Read Article function

### PR DESCRIPTION
**Pull request by xQuByte**

### CODE REVIEW

**Comment by brunnopleffken** [comment]
This is great! The "read" page now works!!!
Just that small review, and we're ready to go!

And BTW, you've commited `config.php`.

**Comment by xQuByte** [comment]
You right... Can you push this without config file?

**Comment by brunnopleffken** [comment]
No, I can't. But no problems, just remove that slash in URL so I can merge the PR and empty the `config.php` after it's merged.

**Comment by xQuByte** [comment]
Which slash?

**Comment by brunnopleffken** [comment]
The first one, before `articles/read` in `<a>`, otherwise it'll redirect you to a higher dir level.

**Comment by xQuByte** [comment]
Fixed ;)

**Comment by brunnopleffken** [comment]
And merged! Thanks!!! :D

**Pull request merged**
